name: Component Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          # env: host=http://127.0.0.1,apiPort=46096
          spec: cypress/e2e/backEnd.cy.js
          # browser: electron
          wait-on: 'http://localhost:4200/#/home, http://localhost:46096, http://localhost:13596'
          # wait-on-timeout: 60
          timeout-minutes: 5