name: example-wait-on
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:

 wait-v10:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          # wait for the URL to respond
          # using the default parameter
          working-directory: examples/v10/wait-on
          start: npm start
          wait-on: 'http://localhost:4200'