name: integrations tests
on: [push]
jobs:

  smoke:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    strategy:
      fail-fast: false
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node 16.13.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2
      - name: Cypress integration tests
        uses: cypress-io/github-action@v4.1.0
        with:
          install-command: yarn install
          wait-on: 'http://127.0.0.1:4200/#/home'
          wait-on-timeout: 60 # seconds = 6 mins
          config: 'baseUrl=http://127.0.0.1:4200/#/home'
          spec: cypress/e2e/*

  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node 16.13.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2
      - name: Cypress data validation
        uses: cypress-io/github-action@v4.1.0
        with:
          env: VALIDATE_ALL=true
          spec: cypress/e2e/zz-validate-data.cy.js
          start: npm run build:serve:4201
          wait-on: 'http://127.0.0.1:4201/#/home'
          wait-on-timeout: 500 # seconds = 6 mins
          config: 'baseUrl=http://127.0.0.1:4201/#/home'